### ISSUE TITLE
How to specify arrival rates in the client?

### ISSUE THREAD

**Issue by PasinduTennage** [haochenpan/rabia#30]
I am trying to do a performance analysis of Rabia, and wanted to do an open loop test with different arrival rates. 

In `roles/client/client.go`  in `OpenLoopClient()`, before sending a request in `sendOneRequest(i int)`, the client sleeps for a fixed inter-arrival-time. However, this is different from the standard `Poisson client arrivals`, so I would like to know if its possible to send Poisson open loop requests; or is there a way I can modify the code to obtain that?

Thanks

**Comment by haochenpan** [comment]
Hi Pasindu,

Totally possible IMO. Do you happen to know a repo/benchmark suite that does Poisson open-loop requests on Multi-Paxos/EPaxos/some storage for my reference, so that I can tell how to adapt that to Rabia?

Best,
Haochen

**Comment by PasinduTennage** [comment]
Hi Haochen,

Thank you for the response.

On the top of my knowledge, EPaxos Revisited (NSDI 2021) evaluates EPaxos and Multi-Paxos using Poisson arrivals of client requests.

Also, I came up with the following code to convert Poisson arrival rate to inter arrival time (which translates to your notion of think time in the client side)

            lambda := float64(cl.arrivalRate) / (1000.0 * 1000.0 * 1000.0) // requests per nano second
		arrivalTime := 0.0

		for true {
			// Get the next probability value from Uniform(0,1)
			p := rand.Float64()

			//Plug it into the inverse of the CDF of Exponential(_lamnbda)
			interArrivalTime := -1 * (math.Log(1.0-p) / lambda)

I also found [this](https://medium.com/@malith.jayasinghe/performance-testing-with-a-think-time-64b6b737e3f9) which discusses about the relationship between client think time and the standard arrival rate

So, in my opinion, if I plug these, in the `sendOneRequest(i int)`, instead of `time.Sleep(time.Duration(Conf.ClientThinkTime) * time.Millisecond)`, then it can achieve Poisson arrivals.

Thanks

**Comment by haochenpan** [comment]
Hi Pasindu, I am not good at probability... I see what you are doing there -- replacing a fixed think time with some random intervals. If you know "Plug it into the inverse of the CDF of Exponential(_lamnbda)" is the right way to generate the random time you need, the implementation LGTM.

**Comment by PasinduTennage** [comment]
Thank you
