### ISSUE TITLE
Definition of mid80Throughput, in the presence of client side batching

### ISSUE THREAD

**Issue by PasinduTennage** [haochenpan/rabia#31]
I ran an open loop experiment, as follows.

1. Clone the repo
2. Modified the `NClients`=3, `ClientBatchSize`=10 and `Rabia_ClosedLoop`=`false` in `rabia/deployment/profile/profile0.sh`
3. The following is the output

```
<nil> WRN  Client Conn.=1 Interval not-NULL Slots=26125 Interval throughput (cmd/sec)=65313 NULL Slots=1 Normal Slots=295054 Svr Id=0 Unmatched Slots=1
<nil> WRN  Client Conn.=1 Interval not-NULL Slots=26115 Interval throughput (cmd/sec)=65288 NULL Slots=1 Normal Slots=295191 Svr Id=1 Unmatched Slots=0
<nil> WRN  Client Conn.=1 Interval not-NULL Slots=26096 Interval throughput (cmd/sec)=65240 NULL Slots=1 Normal Slots=295204 Svr Id=2 Unmatched Slots=0
<nil> WRN  ClientId=1 TotalRecv=1000000 TotalSent=1000000 avgLat=4616435 maxLat=5079694 maxLatIdx=63417 mid80Dur=43.913168199 mid80End=1654616177153984932 mid80RecvTimeDur=39.018847504 mid80Requests=80000 mid80Start=1654616133240816744 mid80Throughput (cmd/sec)=1821.7770040518685 mid80Throughput2 (cmd/sec)=2050.2912084166205 minLat=4227477 p50Lat=4620806 p95Lat=4840542 p99Lat=4992735 recvEnd=1654616181792460398 sendEnd=1654616177487489504 sendStart=1654616133037995977
<nil> WRN  ClientId=0 TotalRecv=1000000 TotalSent=1000000 avgLat=4625584 maxLat=5078731 maxLatIdx=63456 mid80Dur=43.936794374 mid80End=1654616177153773840 mid80RecvTimeDur=39.018529197 mid80Requests=80000 mid80Start=1654616133216979462 mid80Throughput (cmd/sec)=1820.7973781387368 mid80Throughput2 (cmd/sec)=2050.3079343685495 minLat=4229113 p50Lat=4629064 p95Lat=4850382 p99Lat=5004433 recvEnd=1654616181792315112 sendEnd=1654616177451300230 sendStart=1654616133037899793
<nil> WRN  ClientId=2 TotalRecv=1000000 TotalSent=1000000 avgLat=4608395 maxLat=5080453 maxLatIdx=62624 mid80Dur=43.883519311 mid80End=1654616177154144261 mid80RecvTimeDur=39.018827943 mid80Requests=80000 mid80Start=1654616133270624963 mid80Throughput (cmd/sec)=1823.0078456799365 mid80Throughput2 (cmd/sec)=2050.2922362728746 minLat=4230412 p50Lat=4618728 p95Lat=4828899 p99Lat=4983292 recvEnd=1654616181810146751 sendEnd=1654616177521779356 sendStart=1654616133038982731
```

The replica side throughput shows a value close to 65k, where as in the client side it shows 1.8k. This difference comes from the fact that client side throughput is calculated as len(array)/time, so if we multiply the client side throughput by 10, we get more or less equal result.

Is my understanding correct?

Thank you

**Comment by haochenpan** [comment]
Upon receiving a reply, the client calculates the client-batched request's latency (receive time - send time). When the client exits, it has accumulated an array of latencies, each corresponding to a client-batched request, in the order it receives. Similar to EPaxos, we discard the head 10% of the latency array and the tail 10% of the array to factor out ramp-up & ramp-down slowness. In the code, we call  the resulting “middle 80%” array cmdLogs. Then, mid80Throughput = the length of cmdLogs / 
(cmdLogs[last].ReceiveTime - cmdLogs[first].SendTime)

When there’s no batching, mid80Throughput is the estimated throughput at a particular client excluding the ramp-up & ramp-down slowness. When all client batches have the same number of messages (specified by parameter ClientBatchSize),  mid80Throughput * ClientBatchSize is the best-estimated throughput. We use such statistics only for visually inspecting whether all clients are working. And in our experience, using system-side logs to calculate throughput and latencies is easier and more accurate.

**Comment by PasinduTennage** [comment]
Thank you
