### ISSUE TITLE
Error Trying to run Rubia on a single VM - note: module requires Go 1.17

### ISSUE THREAD

**Issue by angelmotta** [haochenpan/rabia#32]
Hello
I am an undergraduate CS Student, studying and reading your paper. I was trying to run Rubia on a single VM following your directions but It fails in step number 3, as I see it throws the error in the "_build_binary_" step of the single.sh file

1. download the project to the default path (see section 1.3)
2. install Rabia and its dependencies
3. check the installation:
cd ./run
. single.sh          # the default parameter runs a Rabia cluster on a single machine for 20 seconds

For the output looks like the _sys_ dependency use a higher go version Go.1.17 as I see in the go.mod of that dependency and Rabia use Go.1.15 according to the install.sh file

What could I do in this case? I am not sure if I _should_ indicate a higher go version in the install.sh or Rabia (1.17) or what is the recommended way to solve this issue?

Thanks in advanced for your assistance.

The complete output error:
_golang.org/x/sys/unix
../../../../pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../../../../pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall_linux.go:1018:20: undefined: unsafe.Slice
../../../../pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall_linux.go:2289:9: undefined: unsafe.Slice
../../../../pkg/mod/golang.org/x/sys@v0.6.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../../../pkg/mod/golang.org/x/sys@v0.6.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
**_note: module requires Go 1.17_**
chmod: cannot access '/home/angelinux/go/src/rabia/rabia': No such file or directory
3. start all servers
-bash: /home/angelinux/go/src/rabia/rabia: No such file or directory
-bash: /home/angelinux/go/src/rabia/rabia: No such file or directory
-bash: /home/angelinux/go/src/rabia/rabia: No such file or directory
-bash: /home/angelinux/go/src/rabia/rabia: No such file or directory
[1]-  Exit 127                RC_Role=svr RC_Index=${idx} RC_SvrIp=${SvrIps[$idx]} RC_PPort=${SvrPPorts[$idx]} RC_NPort=${SvrNPorts[$idx]} RC_Peers=${RC_Peers[@]} ${RCFolder}/rabia
[2]   Exit 127                RC_Role=svr RC_Index=${idx} RC_SvrIp=${SvrIps[$idx]} RC_PPort=${SvrPPorts[$idx]} RC_NPort=${SvrNPorts[$idx]} RC_Peers=${RC_Peers[@]} ${RCFolder}/rabia
[3]   Exit 127                RC_Role=svr RC_Index=${idx} RC_SvrIp=${SvrIps[$idx]} RC_PPort=${SvrPPorts[$idx]} RC_NPort=${SvrNPorts[$idx]} RC_Peers=${RC_Peers[@]} ${RCFolder}/rabia
-bash: /home/angelinux/go/src/rabia/rabia: No such file or directory
Traceback (most recent call last):
  File "/home/angelinux/go/src/rabia/deployment/analysis/analysis.py", line 256, in <module>
    print_statistics()
  File "/home/angelinux/go/src/rabia/deployment/analysis/analysis.py", line 211, in print_statistics
    for param in get_experiments(log_folder):
  File "/home/angelinux/go/src/rabia/deployment/analysis/analysis.py", line 26, in get_experiments
    files = [f for f in listdir(log_folder_path) if isfile(join(log_folder_path, f)) and "log" in f]
FileNotFoundError: [Errno 2] No such file or directory: '/home/angelinux/go/src/rabia/logs'
[4]+  Exit 127                RC_Role=cli RC_Index=${idx} RC_Proxy=${RC_Proxies[$proxy_idx]} ${RCFolder}/rabia_

**Comment by haochenpan** [comment]
Hello,

Thanks for your interest in our work! 

I am not sure how sys package is introduced in the first place. Maybe a Go package [here](https://github.com/haochenpan/rabia/blob/main/deployment/install/install.sh#L70) imports it? If that's the case, I think Rabia also works for Go 1.17; please feel free to change the install.sh script to install the latest Rabia version. If you have time, submit a pull request if you find that works.

**Comment by angelmotta** [comment]
Hello Haochen, thanks for your response. 
I find Rabia very interesting! the goal about reduce the complexity of the implementation is so good and I am studying this topic as my undergraduate thesis.

Syscall package is defined in the main.go file of Rabia [here](https://github.com/haochenpan/rabia/blob/159e0a3c7ae2b9c8aaa826cc6cff7d364579c323/main.go#L28)

According to my review, the _sys_ package showed in the above error is a dependency of the _syscall_ package so sys is defined in the go.mod file of [syscall package](https://pkg.go.dev/syscall@go1.15.8)

Seeing the error message, the sys version invoked is _sys@v0.6.0._ I have seen the go.mod file of the sys package [here](https://cs.opensource.google/go/x/sys/+/refs/tags/v0.6.0:go.mod) and it requires Go 1.17 or later so Rabia can not compile it having installed Go version 1.15.8 as defined its install.sh.

Following your suggestion I changed the Go version from 1.15.8 defined in install.sh to the latest Go version 1.20.2 and It works! 

<img width="1719" alt="rabia_running" src="https://user-images.githubusercontent.com/12142884/225411014-a0b110b9-9746-47ef-8e50-784adb93cf4a.png">


I could successfully run Rabia ([step 3](https://github.com/haochenpan/rabia/blob/main/docs/run-rabia.md#2-install-rabia)) with single.sh using a single VM (a humble one with 1GB Ram and 1vCPU) and inspect the performance statistics (btw, pretty cool “Rabia” message in the terminal while it’s starting)

I will submit a pull request with this change.

**Comment by haochenpan** [comment]
Thanks for your thorough investigation and updating the installation script for Rabia! I have merged the PR. If you have any other questions, please feel free to message me on GitHub or through email, and  contact Professor Lewis Tseng : )

**Comment by angelmotta** [comment]
I am very happy to help! It's my first contribution ever! 
I really appreciate your help Haochen! 🙌🏻 I definitely will need some guidance about Rabia so I will message you to get some lights about it and also thank you for mention the Professor Lewis Tseng.
I am just starting so I will continue studying and getting familiar with Rabia. Let's keep in contact! 😃
